apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::679998374111:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
