apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::679998374111:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QDMQFAUHKV2S
      username: build
      groups:
        - system:masters
